<a href="https://colab.research.google.com/github/Nithesh-b/config/blob/master/GAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Submit a zip file containing dcgan.py file, this notebook and the final image generated during training without changing its name.

In [ ]:
### Import numpy, mnist dataset or fashion_mnist dataset (your choice), dcgan.py and image_helper.py file
import numpy as np
from keras.datasets import fashion_mnist
from tensorflow.keras.optimizers import Adam
import sys  
sys.path.insert(0, '/content/sample_data')
from dcgan import DCGAN
from image_helper import ImageHelper

(X,_),(_,_) =  fashion_mnist.load_data()
### Normalize the X
print (X)
X_train = X / 127.5 - 1.
print ("----------------------")
print (X_train)
X_train = np.expand_dims(X_train, axis=3)
print ("----------------------")
print (X_train[0])
img_obj = ImageHelper()
### Call the DCGAN class object passing parameters image_shape, generator_input_dim, image_helper class object, and number of channels of mnist data 
generative_advarsial_network = DCGAN(X_train[0].shape, 100, img_obj,1)

### Train the X_train with batchsize of your choice for minimum 30000 epochs
generative_advarsial_network.train(30000, X_train, batch_size=32)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
----------------------
[[[-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  ...
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]
  [-1. -1. -1. ... -1. -1. -1.]]

 [[

As the training shall be hours long and you have to experiment a lot to get better generated images, it's recommended to use this [free chrome extension](https://chrome.google.com/webstore/detail/colab-auto-reconnect/nbcihfbfamjlfiopdcemmohoojdecjid) or [free firefox extenstion](https://addons.mozilla.org/en-US/firefox/addon/colab-auto-reconnect/), it was built during such frustrating GANs training.